---
# Try to create directory as current ansible_user, repeat as root if failed.

- block:
    - name: Ensure directory exists.
      file:
        path: '{{ dir_path }}'
        state: directory
        mode: 0755

  rescue:
    - name: Ensure directory exists, as root.
      file:
        path: '{{ dir_path }}'
        state: directory
        mode: 0755
      become: true
